# Generated by Django 3.0.2 on 2020-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('Беларусь', 'Беларусь'), ('Россия', 'Россия'), ('Чехия', 'Чехия'), ('Румыния', 'Румыния'), ('США', 'США'), ('Камбоджа', 'Камбоджа')], default='Беларусь', max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='wood/')),
            ],
        ),
    ]
