# Generated by Django 3.0.2 on 2020-01-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='photo',
            field=models.ImageField(height_field=100, upload_to='wood/', width_field=100),
        ),
    ]
