# Generated by Django 3.0.2 on 2020-01-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20200129_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='photo',
        ),
    ]
