# Generated by Django 3.0.2 on 2020-01-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_remove_sample_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Саговниковидные', 'Саговниковидные'), ('Гинкговидные', 'Гинкговидные'), ('Хвойные', 'Хвойные'), ('Гнетовидные', 'Гнетовидные'), ('Цветковые растения', 'Цветковые растения')], default='Цветковые растения', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Беларусь', 'Беларусь'), ('Россия', 'Россия'), ('Чехия', 'Чехия'), ('Румыния', 'Румыния'), ('США', 'США'), ('Камбоджа', 'Камбоджа')], default='Беларусь', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='photo',
            field=models.ImageField(blank=True, upload_to='wood/'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='family',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='genus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sample',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.Department'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='samples.PickupLocation'),
        ),
    ]
