# Generated by Django 3.0.2 on 2020-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20200130_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(choices=[('Беларусь', 'Беларусь'), ('Россия', 'Россия'), ('Чехия', 'Чехия'), ('Румыния', 'Румыния'), ('США', 'США'), ('Камбоджа', 'Камбоджа')], default='Беларусь', max_length=20),
        ),
    ]
