# Generated by Django 3.0.2 on 2020-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_auto_20200130_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
