# Generated by Django 3.0.2 on 2020-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20200130_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
